language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install -qq libboost-dev
before_script:
  - autoreconf -i
script: ./configure && make
branches:
  only:
    - master
notifications:
  recipients:
    - wojdyr@gmail.com
  email:
    on_success: change
    on_failure: always
